name: ML Pipeline on Push

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python src/train.py

    - name: Test Model
      run: |
        python src/predict.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model/iris_model.pkl  # Adjust path based on where you save the model
